# Generated by Django 4.2.5 on 2023-11-14 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_consulta', models.DateField()),
                ('fecha_posible_alta', models.DateField()),
                ('close_date', models.DateTimeField(null=True)),
                ('tag', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('tratamiento_administrado', models.CharField(max_length=200)),
                ('via_de_administracion', models.CharField(max_length=100)),
                ('plan_de_manejo', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'erp_consultas_medica',
                'ordering': ['-created_at', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.consulta')),
            ],
            options={
                'verbose_name': 'Evolucion',
                'verbose_name_plural': 'Evoluciones',
                'db_table': 'erp_evolucion_medica',
            },
        ),
        migrations.CreateModel(
            name='InformeDePartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_casa', models.CharField(max_length=200)),
                ('equipo_visita', models.CharField(max_length=200)),
                ('fecha_calendario', models.DateField()),
                ('jornada', models.CharField(max_length=100, null=True)),
                ('generalidades', models.TextField(null=True)),
                ('fase_ofensiva', models.TextField(null=True)),
                ('fase_defensiva', models.TextField(null=True)),
                ('abp', models.TextField(null=True)),
                ('notas_partido', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Informe de partido',
                'verbose_name_plural': 'Informe de partidos',
                'db_table': 'erp_informes_de_partidos',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.consulta')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'erp_visitas_medicas',
            },
        ),
        migrations.CreateModel(
            name='InformeDeJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calendario', models.DateField()),
                ('rival', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=100)),
                ('notas_partido', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe Individual',
                'verbose_name_plural': 'Informes Individuales',
                'db_table': 'erp_informes_individuales',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='medicina/imagenes/')),
                ('evolucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.evolucion')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'db_table': 'erp_evolucion_imagenes',
            },
        ),
        migrations.CreateModel(
            name='Hallazgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.consulta')),
            ],
            options={
                'verbose_name': 'hallazgo',
                'verbose_name_plural': 'Hallazgos',
                'db_table': 'erp_hallazgos_medicos',
            },
        ),
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('humor_matutino', models.CharField(max_length=50)),
                ('horas_dormidas', models.IntegerField()),
                ('minutos_dormidos', models.IntegerField()),
                ('calidad_descanso', models.CharField(max_length=55)),
                ('nivel_eustres', models.IntegerField()),
                ('nivel_distres', models.IntegerField()),
                ('preparacion_mental', models.IntegerField()),
                ('enfoque_externo', models.CharField(max_length=2)),
                ('enfoque_interno', models.CharField(max_length=2)),
                ('comentarios_adicionales', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'db_table': 'erp_quiz_psicologia',
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='medicina/archivos/')),
                ('evolucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.evolucion')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'erp_evolucion_archivos',
            },
        ),
    ]
